version: "3.1"
services:
  testproject-agent:
    image: testproject/agent:latest
    container_name: coringa-agente
    depends_on:
      - chrome
      - firefox
    volumes:
      - C:/Users/capel/OneDrive/Trabalho/Alelo/Automação de Testes/Dockes/Coringa:/var/testproject/agent
    environment:
      TP_API_KEY: "ZtO5PRNIqjyTHcyAGSntt-AudL97YhSiDBxa2sA3iPg1"
      TP_AGENT_ALIAS: "Docker Coringa"
      CHROME: "chrome:4444"
      FIREFOX: "firefox:4444"
  chrome:
    image: selenium/standalone-chrome
    shm_size: '1gb'
  firefox:
    image: selenium/standalone-firefox
    shm_size: '1gb'